server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:file:./data/testdbcity
    driver-class-name: org.h2.Driver
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
weather-service:
  url: http://10.10.5.115:8082/weather/api